### ISSUE TITLE
Does this only work on Debian?

### ISSUE THREAD

**Issue by mrjcleaver** [elmar/ldap-git-backup#1]
I couldn't see it in the instructions but noted the directory and your affiliation.

I'd want to use it on Redhat.

Thanks,
  Martin.

**Comment by xtaran** [comment]
Not yet. But since it uses plain autotools style configuration of paths, it should be easy to install to `/usr/local/` or to package for RPM based distributions. Feel free to contribute a `.spec` file.

I though just noticed that we don't ship a configure script inside the release tar-ball, at least not for 1.0.7. We should change that for the ease of installation.

So if you want to install it to `/usr/local` from a git checkout or tar ball, run `autoreconf -i` inside the untarred or checked out directory and the do the common `./configure && make && make check && make install` dance.

**Comment by xtaran** [comment]
Actually it's clear why the configure script is missing in the release tar ball. Those are just tar balls generated by Github on git tags. It's not the release tar ball build by autotools on `make dist`.

**Comment by mrjcleaver** [comment]
Thanks guys!
